=== open-mpi/hwloc/hwloc/hwloc2.dtd
<!--
  SPDX-License-Identifier: BSD-3-Clause
  Copyright © 2009      CNRS
  Copyright © 2009-2026 Inria.  All rights reserved.
  Copyright © 2009-2011 Université Bordeaux.
  See COPYING in top-level directory.

  This is the DTD for hwloc v2.x XMLs.
 -->

<!ELEMENT topology (object+,distances2*,distances2hetero*,support*,memattr*,cpukind*,info*,memtier*,pci_locality*)>
<!ATTLIST topology version CDATA "">

<!ELEMENT object (page_type*,info*,userdata*,object*)>
<!ATTLIST object type (Machine | Misc | Group | NUMANode | MemCache | Package | Die | L1Cache | L2Cache | L3Cache | L4Cache | L5Cache | L1iCache | L2iCache | L3iCache | Core | PU | Bridge | PCIDev | OSDev) #REQUIRED>
<!ATTLIST object subtype CDATA "" >
<!ATTLIST object os_index CDATA "-1" >
<!ATTLIST object id CDATA "-1" >
<!ATTLIST object gp_index CDATA "-1" >
<!ATTLIST object name CDATA "" >
<!ATTLIST object local_memory CDATA "0" >
<!ATTLIST object cache_size CDATA "0" >
<!ATTLIST object cache_linesize CDATA "0" >
<!ATTLIST object cache_associativity CDATA "0" >
<!ATTLIST object cache_type CDATA "0" >
<!ATTLIST object cache_inclusive CDATA "0" >
<!ATTLIST object cpuset CDATA "0" >
<!ATTLIST object complete_cpuset CDATA "" >
<!ATTLIST object allowed_cpuset CDATA "" >
<!ATTLIST object nodeset CDATA "" >
<!ATTLIST object complete_nodeset CDATA "" >
<!ATTLIST object allowed_nodeset CDATA "" >
<!ATTLIST object depth CDATA "-1" >
<!ATTLIST object kind CDATA "0" >
<!ATTLIST object subkind CDATA "0" >
<!ATTLIST object dont_merge CDATA "0" >
<!ATTLIST object bridge_type CDATA "" >
<!ATTLIST object bridge_pci CDATA "" >
<!ATTLIST object pci_busid CDATA "" >
<!ATTLIST object pci_type CDATA "" >
<!ATTLIST object pci_link_speed CDATA "0." >
<!ATTLIST object osdev_type CDATA "" >

<!ELEMENT info EMPTY>
<!ATTLIST info name CDATA #REQUIRED>
<!ATTLIST info value CDATA #REQUIRED>

<!ELEMENT distances2 (indexes+,u64values+)>
<!ATTLIST distances2 type CDATA #REQUIRED>
<!ATTLIST distances2 nbobjs CDATA #REQUIRED>
<!ATTLIST distances2 indexing CDATA #REQUIRED>
<!ATTLIST distances2 kind CDATA #REQUIRED>
<!ATTLIST distances2 name CDATA "">

<!ELEMENT distances2hetero (indexes+,u64values+)>
<!ATTLIST distances2hetero nbobjs CDATA #REQUIRED>
<!ATTLIST distances2hetero kind CDATA #REQUIRED>
<!ATTLIST distances2hetero name CDATA "">

<!ELEMENT memattr (memattr_value*)>
<!ATTLIST memattr name CDATA #REQUIRED>
<!ATTLIST memattr flags CDATA #REQUIRED>

<!ELEMENT memattr_value EMPTY>
<!ATTLIST memattr_value target_obj_gp_index CDATA "">
<!ATTLIST memattr_value target_obj_type CDATA #REQUIRED>
<!ATTLIST memattr_value value CDATA #REQUIRED>
<!ATTLIST memattr_value initiator_cpuset CDATA "">
<!ATTLIST memattr_value initiator_obj_gp_index CDATA "">
<!ATTLIST memattr_value initiator_obj_type CDATA "">

<!ELEMENT indexes (#PCDATA)>
<!ATTLIST indexes length CDATA #REQUIRED>

<!ELEMENT u64values (#PCDATA)>
<!ATTLIST u64values length CDATA #REQUIRED>

<!ELEMENT userdata (#PCDATA)>
<!ATTLIST userdata name CDATA "" >
<!ATTLIST userdata length CDATA "0" >
<!ATTLIST userdata encoding CDATA "" >

<!ELEMENT support EMPTY>
<!ATTLIST support name CDATA #REQUIRED>
<!ATTLIST support value CDATA "1" >

<!ELEMENT cpukind (info*)>
<!ATTLIST cpukind cpuset CDATA "0">
<!ATTLIST cpukind forced_efficiency CDATA "-1">

<!ELEMENT memtier (info*)>
<!ATTLIST memtier kinds CDATA "0">
<!ATTLIST memtier nodeset CDATA "0">

<!ELEMENT pci_locality EMPTY>
<!ATTLIST pci_locality domain CDATA #REQUIRED>
<!ATTLIST pci_locality bus_min CDATA #REQUIRED>
<!ATTLIST pci_locality bus_max CDATA #REQUIRED>
<!ATTLIST pci_locality cpuset CDATA #REQUIRED>

<!-- ignored since 3.0 -->
<!ELEMENT page_type EMPTY>
<!ATTLIST page_type size CDATA #REQUIRED>
<!ATTLIST page_type count CDATA #REQUIRED>

=== open-mpi/hwloc/doc/images/ppc64-with-smt.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topology SYSTEM "hwloc2.dtd">
<topology version="2.0">
  <object type="Machine" os_index="0" cpuset="0xf0f0f0f0" complete_cpuset="0xf0f0f0f0" allowed_cpuset="0xf0f0f0f0" nodeset="0x00000003" complete_nodeset="0x00000003" allowed_nodeset="0x00000003" gp_index="1">
    <object type="Group" cpuset="0x0000f0f0" complete_cpuset="0x0000f0f0" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="74" kind="1001" subkind="0">
      <object type="NUMANode" os_index="0" cpuset="0x0000f0f0" complete_cpuset="0x0000f0f0" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="2" local_memory="31943819264">
        <page_type size="65536" count="487424"/>
        <page_type size="16777216" count="0"/>
      </object>
      <object type="PU" os_index="4" cpuset="0x00000010" complete_cpuset="0x00000010" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="8"/>
      <object type="PU" os_index="5" cpuset="0x00000020" complete_cpuset="0x00000020" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="9"/>
      <object type="PU" os_index="6" cpuset="0x00000040" complete_cpuset="0x00000040" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="10"/>
      <object type="PU" os_index="7" cpuset="0x00000080" complete_cpuset="0x00000080" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="11"/>
      <object type="PU" os_index="12" cpuset="0x00001000" complete_cpuset="0x00001000" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="16"/>
      <object type="PU" os_index="13" cpuset="0x00002000" complete_cpuset="0x00002000" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="17"/>
      <object type="PU" os_index="14" cpuset="0x00004000" complete_cpuset="0x00004000" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="18"/>
      <object type="PU" os_index="15" cpuset="0x00008000" complete_cpuset="0x00008000" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="19"/>
    </object>
    <object type="Group" cpuset="0xf0f00000" complete_cpuset="0xf0f00000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="75" kind="1001" subkind="0">
      <object type="NUMANode" os_index="1" cpuset="0xf0f00000" complete_cpuset="0xf0f00000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="20" local_memory="33554432000">
        <page_type size="65536" count="512000"/>
        <page_type size="16777216" count="0"/>
      </object>
      <object type="PU" os_index="20" cpuset="0x00100000" complete_cpuset="0x00100000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="26"/>
      <object type="PU" os_index="21" cpuset="0x00200000" complete_cpuset="0x00200000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="27"/>
      <object type="PU" os_index="22" cpuset="0x00400000" complete_cpuset="0x00400000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="28"/>
      <object type="PU" os_index="23" cpuset="0x00800000" complete_cpuset="0x00800000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="29"/>
      <object type="PU" os_index="28" cpuset="0x10000000" complete_cpuset="0x10000000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="34"/>
      <object type="PU" os_index="29" cpuset="0x20000000" complete_cpuset="0x20000000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="35"/>
      <object type="PU" os_index="30" cpuset="0x40000000" complete_cpuset="0x40000000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="36"/>
      <object type="PU" os_index="31" cpuset="0x80000000" complete_cpuset="0x80000000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="37"/>
    </object>
  </object>
</topology>

=== open-mpi/hwloc/tests/hwloc/x86/AMD-K8-SledgeHammer-2xOpteron-250.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topology SYSTEM "hwloc2.dtd">
<topology version="3.0">
  <object type="Machine" os_index="0" cpuset="0x00000003" complete_cpuset="0x00000003" allowed_cpuset="0x00000003" nodeset="0x00000001" complete_nodeset="0x00000001" allowed_nodeset="0x00000001">
    <object type="NUMANode" os_index="0" cpuset="0x00000003" complete_cpuset="0x00000003" nodeset="0x00000001" complete_nodeset="0x00000001"/>
    <object type="Package" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001">
      <info name="CPUVendor" value="AuthenticAMD"/>
      <info name="CPUFamilyNumber" value="15"/>
      <info name="CPUModelNumber" value="5"/>
      <info name="CPUModel" value="AMD Opteron(tm) Processor 250"/>
      <info name="CPUStepping" value="10"/>
      <object type="L2Cache" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" cache_size="1048576" depth="2" cache_linesize="64" cache_associativity="16" cache_type="0">
        <object type="L1Cache" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" cache_size="65536" depth="1" cache_linesize="64" cache_associativity="2" cache_type="1">
          <object type="L1iCache" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" cache_size="65536" depth="1" cache_linesize="64" cache_associativity="2" cache_type="2">
            <object type="Core" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001">
              <object type="PU" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001"/>
            </object>
          </object>
        </object>
      </object>
    </object>
    <object type="Package" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001">
      <info name="CPUVendor" value="AuthenticAMD"/>
      <info name="CPUFamilyNumber" value="15"/>
      <info name="CPUModelNumber" value="5"/>
      <info name="CPUModel" value="AMD Opteron(tm) Processor 250"/>
      <info name="CPUStepping" value="10"/>
      <object type="L2Cache" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" cache_size="1048576" depth="2" cache_linesize="64" cache_associativity="16" cache_type="0">
        <object type="L1Cache" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" cache_size="65536" depth="1" cache_linesize="64" cache_associativity="2" cache_type="1">
          <object type="L1iCache" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" cache_size="65536" depth="1" cache_linesize="64" cache_associativity="2" cache_type="2">
            <object type="Core" os_index="0" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001">
              <object type="PU" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001"/>
            </object>
          </object>
        </object>
      </object>
    </object>
  </object>
  <info name="Backend" value="x86"/>
</topology>

=== open-mpi/hwloc/tests/hwloc/linux/allowed/test1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topology SYSTEM "hwloc2.dtd">
<topology version="3.0">
  <object type="Machine" os_index="0" cpuset="0x0000747e" complete_cpuset="0x0000ffff" allowed_cpuset="0x0000747e" nodeset="0x00000006" complete_nodeset="0x0000000f" allowed_nodeset="0x00000006">
    <object type="Group" cpuset="0x0000000e" complete_cpuset="0x0000000f" nodeset="0x0" complete_nodeset="0x00000001" kind="1001" subkind="0">
      <object type="Core" os_index="0" cpuset="0x00000002" complete_cpuset="0x00000003" nodeset="0x0" complete_nodeset="0x00000001">
        <object type="PU" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x0" complete_nodeset="0x00000001"/>
      </object>
      <object type="Core" os_index="1" cpuset="0x0000000c" complete_cpuset="0x0000000c" nodeset="0x0" complete_nodeset="0x00000001">
        <object type="PU" os_index="2" cpuset="0x00000004" complete_cpuset="0x00000004" nodeset="0x0" complete_nodeset="0x00000001"/>
        <object type="PU" os_index="3" cpuset="0x00000008" complete_cpuset="0x00000008" nodeset="0x0" complete_nodeset="0x00000001"/>
      </object>
    </object>
    <object type="Group" cpuset="0x00000070" complete_cpuset="0x000000f0" nodeset="0x00000002" complete_nodeset="0x00000002" kind="1001" subkind="0">
      <object type="NUMANode" os_index="1" cpuset="0x00000070" complete_cpuset="0x000000f0" nodeset="0x00000002" complete_nodeset="0x00000002" local_memory="1073741824">
        <page_type size="4096" count="262144"/>
      </object>
      <object type="Core" os_index="2" cpuset="0x00000030" complete_cpuset="0x00000030" nodeset="0x00000002" complete_nodeset="0x00000002">
        <object type="PU" os_index="4" cpuset="0x00000010" complete_cpuset="0x00000010" nodeset="0x00000002" complete_nodeset="0x00000002"/>
        <object type="PU" os_index="5" cpuset="0x00000020" complete_cpuset="0x00000020" nodeset="0x00000002" complete_nodeset="0x00000002"/>
      </object>
      <object type="Core" os_index="3" cpuset="0x00000040" complete_cpuset="0x000000c0" nodeset="0x00000002" complete_nodeset="0x00000002">
        <object type="PU" os_index="6" cpuset="0x00000040" complete_cpuset="0x00000040" nodeset="0x00000002" complete_nodeset="0x00000002"/>
      </object>
    </object>
    <object type="Group" cpuset="0x00000400" complete_cpuset="0x00000f00" nodeset="0x00000004" complete_nodeset="0x00000004" kind="1001" subkind="0">
      <object type="NUMANode" os_index="2" cpuset="0x00000400" complete_cpuset="0x00000f00" nodeset="0x00000004" complete_nodeset="0x00000004" local_memory="1073741824">
        <page_type size="4096" count="262144"/>
      </object>
      <object type="Core" os_index="5" cpuset="0x00000400" complete_cpuset="0x00000c00" nodeset="0x00000004" complete_nodeset="0x00000004">
        <object type="PU" os_index="10" cpuset="0x00000400" complete_cpuset="0x00000400" nodeset="0x00000004" complete_nodeset="0x00000004"/>
      </object>
    </object>
    <object type="Group" cpuset="0x00007000" complete_cpuset="0x0000f000" nodeset="0x0" complete_nodeset="0x00000008" kind="1001" subkind="0">
      <object type="Core" os_index="6" cpuset="0x00003000" complete_cpuset="0x00003000" nodeset="0x0" complete_nodeset="0x00000008">
        <object type="PU" os_index="12" cpuset="0x00001000" complete_cpuset="0x00001000" nodeset="0x0" complete_nodeset="0x00000008"/>
        <object type="PU" os_index="13" cpuset="0x00002000" complete_cpuset="0x00002000" nodeset="0x0" complete_nodeset="0x00000008"/>
      </object>
      <object type="Core" os_index="7" cpuset="0x00004000" complete_cpuset="0x0000c000" nodeset="0x0" complete_nodeset="0x00000008">
        <object type="PU" os_index="14" cpuset="0x00004000" complete_cpuset="0x00004000" nodeset="0x0" complete_nodeset="0x00000008"/>
      </object>
    </object>
  </object>
  <info name="Backend" value="Synthetic"/>
  <info name="SyntheticDescription" value="numa:4 core:2 pu:2"/>
  <info name="LinuxCgroup" value="/dummy"/>
</topology>

=== open-mpi/hwloc/tests/hwloc/xml/8intel64-4n2t-memattrs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topology SYSTEM "hwloc2.dtd">
<topology version="3.0">
  <object type="Machine" os_index="0" cpuset="0x000000ff" complete_cpuset="0x000000ff" allowed_cpuset="0x000000ff" nodeset="0x0000000f" complete_nodeset="0x0000000f" allowed_nodeset="0x0000000f" gp_index="1" id="obj1">
    <object type="Group" cpuset="0x00000003" complete_cpuset="0x00000003" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="5" id="obj5" kind="1001" subkind="0">
      <object type="NUMANode" os_index="0" cpuset="0x00000003" complete_cpuset="0x00000003" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="4" id="obj4" local_memory="1073741824"/>
      <object type="PU" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="2" id="obj2"/>
      <object type="PU" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="3" id="obj3"/>
    </object>
    <object type="Group" cpuset="0x0000000c" complete_cpuset="0x0000000c" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="9" id="obj9" kind="1001" subkind="0">
      <object type="NUMANode" os_index="1" cpuset="0x0000000c" complete_cpuset="0x0000000c" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="8" id="obj8" local_memory="1073741824"/>
      <object type="PU" os_index="2" cpuset="0x00000004" complete_cpuset="0x00000004" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="6" id="obj6"/>
      <object type="PU" os_index="3" cpuset="0x00000008" complete_cpuset="0x00000008" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="7" id="obj7"/>
    </object>
    <object type="Group" cpuset="0x00000030" complete_cpuset="0x00000030" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="13" id="obj13" kind="1001" subkind="0">
      <object type="NUMANode" os_index="2" cpuset="0x00000030" complete_cpuset="0x00000030" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="12" id="obj12" local_memory="1073741824"/>
      <object type="PU" os_index="4" cpuset="0x00000010" complete_cpuset="0x00000010" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="10" id="obj10"/>
      <object type="PU" os_index="5" cpuset="0x00000020" complete_cpuset="0x00000020" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="11" id="obj11"/>
    </object>
    <object type="Group" cpuset="0x000000c0" complete_cpuset="0x000000c0" nodeset="0x00000008" complete_nodeset="0x00000008" gp_index="17" id="obj17" kind="1001" subkind="0">
      <object type="NUMANode" os_index="3" cpuset="0x000000c0" complete_cpuset="0x000000c0" nodeset="0x00000008" complete_nodeset="0x00000008" gp_index="16" id="obj16" local_memory="1073741824"/>
      <object type="PU" os_index="6" cpuset="0x00000040" complete_cpuset="0x00000040" nodeset="0x00000008" complete_nodeset="0x00000008" gp_index="14" id="obj14"/>
      <object type="PU" os_index="7" cpuset="0x00000080" complete_cpuset="0x00000080" nodeset="0x00000008" complete_nodeset="0x00000008" gp_index="15" id="obj15"/>
    </object>
  </object>
  <support name="custom.exported_support"/>
  <memattr name="Bandwidth" flags="5">
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="8" value="20" initiator_cpuset="0x000000ff"/>
  </memattr>
  <memattr name="foobar" flags="6">
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="4" value="2345" initiator_obj_gp_index="15" initiator_obj_type="PU"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="4" value="10" initiator_cpuset="0x00000003"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="8" value="20" initiator_cpuset="0x00000003"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="12" value="30" initiator_cpuset="0x00000003"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="12" value="123" initiator_cpuset="0x00000011"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="16" value="40" initiator_cpuset="0x00000003"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="16" value="2345" initiator_cpuset="0x00000011"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="16" value="23456" initiator_cpuset="0x00000012"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="16" value="23456" initiator_obj_gp_index="13" initiator_obj_type="Group"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="16" value="789" initiator_obj_gp_index="12" initiator_obj_type="NUMANode"/>
  </memattr>
  <memattr name="barnoinit" flags="1">
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="16" value="2345"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="4" value="10"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="8" value="2345"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="12" value="23456"/>
    <memattr_value target_obj_type="PU" target_obj_gp_index="2" value="478945"/>
    <memattr_value target_obj_type="Group" target_obj_gp_index="17" value="789"/>
  </memattr>
  <memattr name="coincoin" flags="5"/>
  <info name="Backend" value="Synthetic"/>
  <info name="SyntheticDescription" value="node:4 pu:2"/>
  <memtier kinds="0" nodeset="0x00000002"/>
  <memtier kinds="0" nodeset="0x0000000d"/>
</topology>

=== open-mpi/hwloc/tests/hwloc/x86/Intel-CPUID.1A-1p2co2t.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topology SYSTEM "hwloc2.dtd">
<topology version="3.0">
  <object type="Machine" os_index="0" cpuset="0x0000000f" complete_cpuset="0x0000000f" allowed_cpuset="0x0000000f" nodeset="0x00000001" complete_nodeset="0x00000001" allowed_nodeset="0x00000001">
    <object type="Package" os_index="0" cpuset="0x0000000f" complete_cpuset="0x0000000f" nodeset="0x00000001" complete_nodeset="0x00000001">
      <info name="CPUVendor" value="GenuineIntel"/>
      <info name="CPUFamilyNumber" value="6"/>
      <info name="CPUModelNumber" value="142"/>
      <info name="CPUModel" value="Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz"/>
      <info name="CPUStepping" value="9"/>
      <object type="NUMANode" os_index="0" cpuset="0x0000000f" complete_cpuset="0x0000000f" nodeset="0x00000001" complete_nodeset="0x00000001"/>
      <object type="L3Cache" cpuset="0x0000000f" complete_cpuset="0x0000000f" nodeset="0x00000001" complete_nodeset="0x00000001" cache_size="4194304" depth="3" cache_linesize="64" cache_associativity="16" cache_type="0" cache_inclusive="1">
        <object type="L2Cache" cpuset="0x00000005" complete_cpuset="0x00000005" nodeset="0x00000001" complete_nodeset="0x00000001" cache_size="262144" depth="2" cache_linesize="64" cache_associativity="4" cache_type="0">
          <object type="L1Cache" cpuset="0x00000005" complete_cpuset="0x00000005" nodeset="0x00000001" complete_nodeset="0x00000001" cache_size="32768" depth="1" cache_linesize="64" cache_associativity="8" cache_type="1">
            <object type="L1iCache" cpuset="0x00000005" complete_cpuset="0x00000005" nodeset="0x00000001" complete_nodeset="0x00000001" cache_size="32768" depth="1" cache_linesize="64" cache_associativity="8" cache_type="2">
              <object type="Core" os_index="0" cpuset="0x00000005" complete_cpuset="0x00000005" nodeset="0x00000001" complete_nodeset="0x00000001">
                <object type="PU" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001"/>
                <object type="PU" os_index="2" cpuset="0x00000004" complete_cpuset="0x00000004" nodeset="0x00000001" complete_nodeset="0x00000001"/>
              </object>
            </object>
          </object>
        </object>
        <object type="L2Cache" cpuset="0x0000000a" complete_cpuset="0x0000000a" nodeset="0x00000001" complete_nodeset="0x00000001" cache_size="262144" depth="2" cache_linesize="64" cache_associativity="4" cache_type="0">
          <object type="L1Cache" cpuset="0x0000000a" complete_cpuset="0x0000000a" nodeset="0x00000001" complete_nodeset="0x00000001" cache_size="32768" depth="1" cache_linesize="64" cache_associativity="8" cache_type="1">
            <object type="L1iCache" cpuset="0x0000000a" complete_cpuset="0x0000000a" nodeset="0x00000001" complete_nodeset="0x00000001" cache_size="32768" depth="1" cache_linesize="64" cache_associativity="8" cache_type="2">
              <object type="Core" os_index="1" cpuset="0x0000000a" complete_cpuset="0x0000000a" nodeset="0x00000001" complete_nodeset="0x00000001">
                <object type="PU" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001"/>
                <object type="PU" os_index="3" cpuset="0x00000008" complete_cpuset="0x00000008" nodeset="0x00000001" complete_nodeset="0x00000001"/>
              </object>
            </object>
          </object>
        </object>
      </object>
    </object>
  </object>
  <cpukind cpuset="0x00000003" forced_efficiency="0">
    <info name="CoreType" value="IntelAtom"/>
  </cpukind>
  <cpukind cpuset="0x0000000c" forced_efficiency="1">
    <info name="CoreType" value="IntelCore"/>
  </cpukind>
  <info name="Backend" value="x86"/>
</topology>

=== open-mpi/hwloc/doc/images/ppc64-without-smt.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topology SYSTEM "hwloc2.dtd">
<topology version="2.0">
  <object type="Machine" os_index="0" cpuset="0x50505050" complete_cpuset="0xf0f0f0f0" allowed_cpuset="0x50505050" nodeset="0x00000003" complete_nodeset="0x00000003" allowed_nodeset="0x00000003" gp_index="1">
    <object type="Group" cpuset="0x00005050" complete_cpuset="0x00005050" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="42" kind="1001" subkind="0">
      <object type="NUMANode" os_index="0" cpuset="0x00005050" complete_cpuset="0x00005050" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="2" local_memory="31943819264">
        <page_type size="65536" count="487424"/>
        <page_type size="16777216" count="0"/>
      </object>
      <object type="PU" os_index="4" cpuset="0x00000010" complete_cpuset="0x00000010" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="6"/>
      <object type="PU" os_index="6" cpuset="0x00000040" complete_cpuset="0x00000040" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="7"/>
      <object type="PU" os_index="12" cpuset="0x00001000" complete_cpuset="0x00001000" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="10"/>
      <object type="PU" os_index="14" cpuset="0x00004000" complete_cpuset="0x00004000" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="11"/>
    </object>
    <object type="Group" cpuset="0x50500000" complete_cpuset="0x50500000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="43" kind="1001" subkind="0">
      <object type="NUMANode" os_index="1" cpuset="0x50500000" complete_cpuset="0x50500000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="12" local_memory="33554432000">
        <page_type size="65536" count="512000"/>
        <page_type size="16777216" count="0"/>
      </object>
      <object type="PU" os_index="20" cpuset="0x00100000" complete_cpuset="0x00100000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="16"/>
      <object type="PU" os_index="22" cpuset="0x00400000" complete_cpuset="0x00400000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="17"/>
      <object type="PU" os_index="28" cpuset="0x10000000" complete_cpuset="0x10000000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="20"/>
      <object type="PU" os_index="30" cpuset="0x40000000" complete_cpuset="0x40000000" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="21"/>
    </object>
  </object>
</topology>
